export const SET_PLAYERS_INFO = 'SET_PLAYERS_INFO';
export const SET_GAME_ROOM_ID = 'SET_GAME_ROOM_ID';
export const SET_GAME_LOBBY_PHASE = 'SET_GAME_LOBBY_PHASE';
export const SET_PLAY_BTN_CLICKED = 'SET_PLAY_BTN_CLICKED';

export const STORE_SOURCE_COORDS = 'STORE_SOURCE_COORDS';
export const STORE_SOURCE_DEST_COORDS = 'STORE_SOURCE_DEST_COORDS';
export const TRIGGER_MAN_MOVEMENT = 'TRIGGER_MAN_MOVEMENT';
export const TRIGGER_REMOVING_MAN_MOVEMENT = 'TRIGGER_REMOVING_MAN_MOVEMENT';
export const MARK_DEST_BOARD_SPOT = 'MARK_DEST_BOARD_SPOT';
export const DESELECT_BOARD_SPOT = "DESELECT_BOARD_SPOT";
export const COMPLETE_REMOVING_MAN_MOVEMENT = "COMPLETE_REMOVING_MAN_MOVEMENT";
export const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";
export const CHANGE_PLAYER_TURN = "CHANGE_PLAYER_TURN";
export const CHANGE_AI_MADE_MILL = "CHANGE_AI_MADE_MILL";
export const SET_PLAYER_MARKER = "SET_PLAYER_MARKER";

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const RESET_BOARD_GAME_STATE = 'RESET_BOARD_GAME_STATE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
